apiVersion: v1
kind: DeploymentConfig
  spec:
    template:
      spec:
        containers:
          - env:
              - name: TRUST_STORE
                value: {{pathToTheTrustStore/trustStore}}
              - name: TRUST_STORE_PASSWORD
                value: {{trustStorePassword}}
              - name: JAVA_TOOL_OPTIONS
                value: '-Djavax.net.ssl.trustStore=$(TRUST_STORE)
                        -Djavax.net.ssl.trustStorePassword=$(TRUST_STORE_PASSWORD)
                        -Djavax.net.ssl.trustStoreType=JKS'
